// <auto-generated />
namespace HID_PDF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddManytoMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddManytoMany));
        
        string IMigrationMetadata.Id
        {
            get { return "202006041544191_Add-Many-to-Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
